# Generated by Django 2.0.8 on 2020-01-31 23:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('tax_info_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RawHTMLBlock(help_text='Add your svg image', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add Hyperlink', required=True))]))], blank=True, null=True),
        ),
    ]
