# Generated by Django 2.2.9 on 2020-04-19 04:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poem_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('poem_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RawHTMLBlock(help_text='Add your svg image', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add Hyperlink', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=wagtail.core.fields.StreamField([('poem_block', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RawHTMLBlock(help_text='Add your svg image', required=True)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add Hyperlink', required=True))]))], blank=True, null=True),
        ),
    ]
