# Generated by Django 2.2.9 on 2020-04-24 06:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200419_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=wagtail.core.fields.StreamField([('poem_body', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
