# Generated by Django 2.2.9 on 2020-04-24 06:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200424_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='main_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
