# Generated by Django 2.2.9 on 2020-04-24 06:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200424_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='author',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
