# Generated by Django 2.2.9 on 2020-04-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_poem_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
    ]
