# Generated by Django 2.2.9 on 2020-04-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='poem_title',
        ),
    ]
