# Generated by Django 2.2.9 on 2020-04-25 05:50

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='scroll_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
