# Generated by Django 2.2.9 on 2020-06-15 02:28

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_poem_semester_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='biography',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='comments',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
