# Generated by Django 2.2.9 on 2020-06-21 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0014_commentts_and_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='scroll_text',
            new_name='button_text',
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_page_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Home Page Image'),
        ),
    ]
