# Generated by Django 2.2.9 on 2020-06-22 02:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200621_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_above_the_collection',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
