# Generated by Django 2.2.9 on 2020-06-22 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200622_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='feature_button_text',
        ),
    ]
