# Generated by Django 2.2.9 on 2020-06-23 21:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_homepage_feature_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section_title',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
