# Generated by Django 3.2.11 on 2022-01-24 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0019_homepage_featured_section_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='featured_poem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
